<a href="https://colab.research.google.com/github/dharsanakb/Natural_Language_Processing/blob/main/NLP_Lab_2_Edit_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Custom implementation where Substitution Cost = 2
def weighted_levenshtein(source, target):
    rows = len(source) + 1
    cols = len(target) + 1

    # Initialize Matrix with zeros
    dist = [[0 for x in range(cols)] for x in range(rows)]

    # Initialize first row (Insertion costs: 0 -> j)
    for j in range(1, cols):
        dist[0][j] = j

    # Initialize first column (Deletion costs: i -> 0)
    for i in range(1, rows):
        dist[i][0] = i

    # Fill the matrix (Dynamic Programming)
    for i in range(1, rows):
        for j in range(1, cols):
            # Calculate Substitution Cost
            if source[i-1] == target[j-1]:
                cost = 0 # Match
            else:
                cost = 2 # Substitution Penalty (Weighted)

            dist[i][j] = min(
                dist[i-1][j] + 1,      # Deletion
                dist[i][j-1] + 1,      # Insertion
                dist[i-1][j-1] + cost  # Substitution / Match
            )

    return dist[rows-1][cols-1], dist


print(f"\n--- Weighted Levenshtein (Sub=2) ---")

# Problem 1: FAST -> CATS
source_word = "kitten"
target_word = "sitting"

distance, matrix = weighted_levenshtein(source_word, target_word)

print(f"Distance ('{source_word}' -> '{target_word}'): {distance}")
print("Matrix State:")
print(np.matrix(matrix))

# Example Usage
#print(f"Distance: {weighted_levenshtein('ROSY', 'POSE')}")
#print(f"Distance: {weighted_levenshtein('KITTEN', 'SITTING')}")
#print(f"Distance: {weighted_levenshtein('Execute', 'Intuition')}")


--- Weighted Levenshtein (Sub=2) ---
Distance ('kitten' -> 'sitting'): 5
Matrix State:
[[0 1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7 8]
 [2 3 2 3 4 5 6 7]
 [3 4 3 2 3 4 5 6]
 [4 5 4 3 2 3 4 5]
 [5 6 5 4 3 4 5 6]
 [6 7 6 5 4 5 4 5]]


## Edit Distance using Library

Instead of manually implementing Levenshtein distance, we use a library function. This is commonly used in spell checkers, DNA matching, and NLP preprocessing.

In [ ]:
import nltk
import numpy as np

# ==========================================
# Standard Levenshtein (NLTK)
# ==========================================
# Default NLTK behavior: Substitution Cost = 1
s1 = "kitten"
s2 = "sitting"
dist_nltk = nltk.edit_distance(s1, s2)
print(f"--- Standard NLTK (Sub=1) ---")
print(f"Distance ('{s1}' -> '{s2}'): {dist_nltk}")

--- Standard NLTK (Sub=1) ---
Distance ('kitten' -> 'sitting'): 3


In [ ]:
# Calculate distance with Substitution Cost = 2
dist = nltk.edit_distance("kitten", "sitting", substitution_cost=2)

print(f"Edit Distance: {dist}")

Edit Distance: 5


In [ ]:
import nltk
from nltk.corpus import words
from nltk.metrics.distance import edit_distance

# Download the 'words' corpus if not already available
nltk.download('words')
correct_words = set(words.words())

def custom_autocorrect(word, correct_words):
    # Find the word in correct_words with the minimum edit distance
    suggestion = min(correct_words, key=lambda cw: edit_distance(word, cw))
    return suggestion

# Example
misspelled_word = "mistaneyl"
correction = custom_autocorrect(misspelled_word, correct_words)
print(f"'{misspelled_word}' corrected to '{correction}'")

'mistaneyl' corrected to 'mistiness'
